version: "2"
services:
  goof:
    #build: .
    container_name: goof
    image: michaelbraunbass/goof-argo
    environment:
      - DOCKER=1
    ports:
      - "3001:3001"
      - "9229:9229"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - "27017:27017"
  mysql:
    container_name: mysql
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acme
    ports:
      - "3306:3306"
