apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector: 
    matchLabels:
      app: mysql
  replicas: 1 
  template:
    metadata:
      labels: 
        app: mysql
    spec:
      containers:
      - image: mysql:5
        args:
          - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: goof-msql
        ports:
        - containerPort: 3306
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: root
         - name: MYSQL_DATABASE
           value: acme
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
   - port: 3306
     targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP