name: Deployment Action
on:
  pull_request:
    types: [opened, reopened]

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk 
      run: |
         sudo npm install -g snyk

    #Run Snyk Code
    - name: Run Snyk Container
      run: |
         snyk code test --severity-threshold=high
      continue-on-error: true  

    #Install Dependencies and Run Snyk SCA
    - name: Run Snyk Container
      run: |
         npm i
         snyk test --severity-threshold=high
      continue-on-error: true  

    # Docker Build
    - name: Build Container     
      run: |
         docker build .  -t michaelbraunbass/goof-argo

    # Run Snyk Container     
    - name: Run Snyk Container
      run: |
         snyk container test --file=Dockerfile michaelbraunbass/goof-argo --app-vulns --severity-threshold=high
         snyk container monitor michaelbraunbass/goof-argo
      continue-on-error: true  

    - name: Login and Push to Dockerhub
      run: |
        docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}       
        docker push michaelbraunbass/goof-argo

